### ISSUE TITLE
Prepend http:// to URLs submitted if they don't have them already

### ISSUE THREAD

**Issue by jedsundwall** [measuredvoice/ringsail#1]
If someone tries verify twitter.com/usagov, we should let them, even though they failed to include http://

**Comment by globalspin** [comment]
Rephrased: If the service_url does not start with http:// or https://, prepend http:// before proceeding.

This may still result in an error or a failed service match (if the URL is otherwise incorrect), but that's not covered by this issue.

**Comment by jedsundwall** [comment]
Thank you for rephrasing. I want to become more precise when writing about these things, so any guidance is very welcome. 

And yes, I understand this may still trigger errors, but I think this will be a common case for people.
