### ISSUE TITLE
Error message on Gobierno verify form should be in spanish

### ISSUE THREAD

**Issue by jedsundwall** [measuredvoice/ringsail#16]
E.g. the error message at the top of http://ringdev.measuredvoice.com/gobierno/verificar?utf8=%E2%9C%93&service_url=test

Translation of error forthcoming. 
@huboard:{"order":13.0}

**Comment by globalspin** [comment]
The translation for this error has been applied. There is a second error that can be translated; it's currently marked with a TODO.
