### ISSUE TITLE
Task - Add cancel button to outlets/add

### ISSUE THREAD

**Issue by jedsundwall** [measuredvoice/ringsail#17]
The cancel button should go to the "verify" page for the same URL. E.g. http://localhost:3000/howto/find?auth_token=96d4b16909f5c79f1e73a79cf9b9d034&service_url=http%3A%2F%2Ftwitter.com%2Fusagov
@huboard:{"order":17.0}

**Comment by globalspin** [comment]
Verified this on ringdev.
