### ISSUE TITLE
Ringsail does not distinguish between twitter.com/usagov and facebook.com/usagov

### ISSUE THREAD

**Issue by jedsundwall** [measuredvoice/ringsail#2]
I just tried to enter http://facebook.com/usagov to my instance of Ringsail. I got the following error:

Mysql2::Error: Duplicate entry 'usagov' for key 'index_outlets_on_service_id_and_account': INSERT INTO `outlets` (`account`, `created_at`, `info_url`, `language`, `organization`, `service`, `service_url`, `updated_at`, `updated_by`) VALUES ('usagov', '2011-12-14 18:42:52', 'http://USA.gov', 'English', 'USA.gov', 'facebook', 'http://facebook.com/usagov', '2011-12-14 18:42:52', 'jed.sundwall@gsa.gov')

It looks like we'll need to distinguish between usernames as entered on different outlets within MySQL.

Let me know if you need further clarification on this.

**Comment by globalspin** [comment]
The database had an old, unneeded validation on the outlets table. I've removed it. Thanks for catching this.
