### ISSUE TITLE
Users should be able to paste a GitHub repo URL to verify the owner of the repo

### ISSUE THREAD

**Issue by jedsundwall** [measuredvoice/ringsail#26]
If a user tries to paste https://github.com/measuredvoice/ringsail or https://github.com/measuredvoice/ringsail/issues/new to the registry, the registry should recognize the account URL as https://github.com/measuredvoice/

Essentially, change the regex in the github service file to parse out github.com/accountname from any repo URL.

**Comment by globalspin** [comment]
This should be fixed. You can verify it on ringdev now.

http://ringdev.measuredvoice.com/social-media/social-media-registry/accounts/find?utf8=%E2%9C%93&service_url=https%3A%2F%2Fgithub.com%2FGeneralServicesAdministration%2Fringsail%2Fissues%2Fnew

**Comment by jedsundwall** [comment]
VERIFIED
